### ISSUE TITLE
 Cannot find module 'pdftk'

### ISSUE THREAD

**Issue by CEXKSharma** [johntayl/pdffiller#32]
I install this library and install the pdftk as well. but, for some reasons it keeps saying the message below. Could anyone please help me to run this library. Thanks.

module.js:340
    throw err;
          ^
Error: Cannot find module 'pdftk'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by whitef0x0** [comment]
You must install pdftk before using this npm module
